#!/usr/bin/env python3
"""
Final cleanup script to translate remaining Korean comments
"""
import os
import re

def final_korean_cleanup():
    """Final pass to translate common Korean patterns"""
    
    files_to_process = [
        'config.py',
        'pipeline.py', 
        'index/build_graph.py',
        'index/edge_embedding.py',
        'index/graph_construction.py',
        'generate/graph_based_rag_short.py'
    ]
    
    # Common Korean to English translations
    translations = {
        # Print statements
        '입력 파일을 찾을 수 없습니다': 'Input file not found',
        '환경 변수': 'Environment variable',
        '를 설정해야 합니다': ' must be set',
        '생성 완료': 'creation completed',
        '처리 중': 'processing',
        '실행': 'Execute',
        '완료': 'completed',
        '시작': 'start',
        '종료': 'end',
        '오류': 'error',
        '성공': 'success',
        '실패': 'failed',
        '로드': 'load',
        '저장': 'save',
        '생성': 'create',
        '삭제': 'delete',
        '수정': 'modify',
        '확인': 'check',
        '검증': 'validate',
        '처리': 'process',
        '변환': 'convert',
        '추출': 'extract',
        '분석': 'analyze',
        '계산': 'calculate',
        '측정': 'measure',
        '평가': 'evaluate',
        '테스트': 'test',
        '디버그': 'debug',
        '최적화': 'optimize',
        '개선': 'improve',
        '업데이트': 'update',
        '업그레이드': 'upgrade',
        '다운그레이드': 'downgrade',
        '설치': 'install',
        '제거': 'remove',
        '정리': 'cleanup',
        '초기화': 'initialize',
        '재설정': 'reset',
        '백업': 'backup',
        '복원': 'restore',
        '동기화': 'synchronize',
        '연결': 'connect',
        '연결 해제': 'disconnect',
        '로그인': 'login',
        '로그아웃': 'logout',
        '인증': 'authenticate',
        '권한': 'permission',
        '보안': 'security',
        '암호화': 'encrypt',
        '복호화': 'decrypt',
        '압축': 'compress',
        '압축 해제': 'decompress',
        '임시': 'temporary',
        '영구': 'permanent',
        '공용': 'public',
        '비공개': 'private',
        '공개': 'public',
        '숨김': 'hidden',
        '표시': 'display',
        '보기': 'view',
        '편집': 'edit',
        '복사': 'copy',
        '붙여넣기': 'paste',
        '잘라내기': 'cut',
        '되돌리기': 'undo',
        '다시 실행': 'redo',
        '찾기': 'find',
        '바꾸기': 'replace',
        '정렬': 'sort',
        '필터': 'filter',
        '그룹': 'group',
        '분류': 'classify',
        '범주': 'category',
        '태그': 'tag',
        '라벨': 'label',
        '이름': 'name',
        '제목': 'title',
        '설명': 'description',
        '내용': 'content',
        '본문': 'body',
        '머리말': 'header',
        '꼬리말': 'footer',
        '사이드바': 'sidebar',
        '네비게이션': 'navigation',
        '메뉴': 'menu',
        '도구': 'tool',
        '기능': 'function',
        '옵션': 'option',
        '설정': 'setting',
        '구성': 'configuration',
        '환경': 'environment',
        '시스템': 'system',
        '플랫폼': 'platform',
        '운영체제': 'operating system',
        '브라우저': 'browser',
        '클라이언트': 'client',
        '서버': 'server',
        '데이터베이스': 'database',
        '파일': 'file',
        '폴더': 'folder',
        '디렉터리': 'directory',
        '경로': 'path',
        '위치': 'location',
        '주소': 'address',
        '링크': 'link',
        '연결': 'connection',
        '네트워크': 'network',
        '인터넷': 'internet',
        '웹': 'web',
        '사이트': 'site',
        '페이지': 'page',
        '문서': 'document',
        '텍스트': 'text',
        '이미지': 'image',
        '사진': 'photo',
        '그림': 'picture',
        '비디오': 'video',
        '오디오': 'audio',
        '음성': 'voice',
        '소리': 'sound',
        '음악': 'music',
        '영화': 'movie',
        '동영상': 'video',
        '애니메이션': 'animation',
        '게임': 'game',
        '앱': 'app',
        '애플리케이션': 'application',
        '프로그램': 'program',
        '소프트웨어': 'software',
        '하드웨어': 'hardware',
        '장치': 'device',
        '기기': 'device',
        '컴퓨터': 'computer',
        '노트북': 'laptop',
        '데스크톱': 'desktop',
        '태블릿': 'tablet',
        '스마트폰': 'smartphone',
        '휴대폰': 'mobile phone',
        '전화': 'phone',
        '팩스': 'fax',
        '이메일': 'email',
        '메시지': 'message',
        '알림': 'notification',
        '경고': 'warning',
        '정보': 'information',
        '데이터': 'data',
        '자료': 'data',
        '통계': 'statistics',
        '분석': 'analysis',
        '보고서': 'report',
        '결과': 'result',
        '출력': 'output',
        '입력': 'input',
        '피드백': 'feedback',
        '응답': 'response',
        '요청': 'request',
        '질문': 'question',
        '답변': 'answer',
        '해결': 'solution',
        '문제': 'problem',
        '이슈': 'issue',
        '버그': 'bug',
        '에러': 'error',
        '예외': 'exception',
        '경고': 'warning',
        '정보': 'info',
        '디버그': 'debug',
        '로그': 'log',
        '기록': 'record',
        '이력': 'history',
        '추적': 'trace',
        '모니터링': 'monitoring',
        '감시': 'surveillance',
        '제어': 'control',
        '관리': 'management',
        '운영': 'operation',
        '실행': 'execution',
        '프로세스': 'process',
        '작업': 'task',
        '업무': 'work',
        '일': 'job',
        '프로젝트': 'project',
        '계획': 'plan',
        '일정': 'schedule',
        '달력': 'calendar',
        '시간': 'time',
        '날짜': 'date',
        '년': 'year',
        '월': 'month',
        '일': 'day',
        '시': 'hour',
        '분': 'minute',
        '초': 'second',
        '주': 'week',
        '주말': 'weekend',
        '평일': 'weekday',
        '휴일': 'holiday',
        '생일': 'birthday',
        '기념일': 'anniversary',
        '이벤트': 'event',
        '모임': 'meeting',
        '회의': 'conference',
        '세미나': 'seminar',
        '워크샵': 'workshop',
        '교육': 'education',
        '훈련': 'training',
        '학습': 'learning',
        '공부': 'study',
        '연구': 'research',
        '개발': 'development',
        '제작': 'production',
        '창작': 'creation',
        '디자인': 'design',
        '예술': 'art',
        '문화': 'culture',
        '역사': 'history',
        '전통': 'tradition',
        '관습': 'custom',
        '규칙': 'rule',
        '법': 'law',
        '정책': 'policy',
        '절차': 'procedure',
        '방법': 'method',
        '방식': 'way',
        '기술': 'technology',
        '과학': 'science',
        '수학': 'mathematics',
        '물리': 'physics',
        '화학': 'chemistry',
        '생물': 'biology',
        '의학': 'medicine',
        '건강': 'health',
        '운동': 'exercise',
        '스포츠': 'sports',
        '여행': 'travel',
        '관광': 'tourism',
        '쇼핑': 'shopping',
        '구매': 'purchase',
        '판매': 'sale',
        '마케팅': 'marketing',
        '광고': 'advertisement',
        '홍보': 'promotion',
        '브랜드': 'brand',
        '제품': 'product',
        '서비스': 'service',
        '고객': 'customer',
        '사용자': 'user',
        '회원': 'member',
        '계정': 'account',
        '프로필': 'profile',
        '개인정보': 'personal information',
        '비밀번호': 'password',
        '암호': 'password',
        '보안': 'security',
        '안전': 'safety',
        '위험': 'risk',
        '주의': 'caution',
        '경계': 'boundary',
        '한계': 'limit',
        '제한': 'restriction',
        '허용': 'allow',
        '금지': 'prohibit',
        '승인': 'approve',
        '거부': 'reject',
        '수락': 'accept',
        '거절': 'decline',
        '선택': 'select',
        '취소': 'cancel',
        '확인': 'confirm',
        '취소': 'cancel',
        '닫기': 'close',
        '열기': 'open',
        '시작': 'start',
        '중지': 'stop',
        '일시정지': 'pause',
        '재생': 'play',
        '재시작': 'restart',
        '새로고침': 'refresh',
        '업데이트': 'update',
        '다운로드': 'download',
        '업로드': 'upload',
        '전송': 'transfer',
        '공유': 'share',
        '배포': 'distribute',
        '발행': 'publish',
        '출판': 'publish',
        '인쇄': 'print',
        '스캔': 'scan',
        '복사': 'copy',
        '이동': 'move',
        '삭제': 'delete',
        '제거': 'remove',
        '추가': 'add',
        '삽입': 'insert',
        '수정': 'modify',
        '편집': 'edit',
        '변경': 'change',
        '업데이트': 'update',
        '개선': 'improve',
        '향상': 'enhance',
        '최적화': 'optimize',
        '조정': 'adjust',
        '설정': 'configure',
        '구성': 'setup',
        '초기화': 'initialize',
        '재설정': 'reset',
        '복원': 'restore',
        '백업': 'backup',
        '저장': 'save',
        '로드': 'load',
        '불러오기': 'load',
        '가져오기': 'import',
        '내보내기': 'export',
        '변환': 'convert',
        '번역': 'translate',
        '해석': 'interpret',
        '분석': 'analyze',
        '계산': 'calculate',
        '측정': 'measure',
        '평가': 'evaluate',
        '검사': 'inspect',
        '확인': 'verify',
        '검증': 'validate',
        '테스트': 'test',
        '시험': 'test',
        '실험': 'experiment',
        '데모': 'demo',
        '예제': 'example',
        '샘플': 'sample',
        '모델': 'model',
        '템플릿': 'template',
        '형식': 'format',
        '양식': 'form',
        '구조': 'structure',
        '패턴': 'pattern',
        '스타일': 'style',
        '테마': 'theme',
        '색상': 'color',
        '크기': 'size',
        '폰트': 'font',
        '글꼴': 'font',
        '텍스트': 'text',
        '문자': 'character',
        '숫자': 'number',
        '기호': 'symbol',
        '아이콘': 'icon',
        '버튼': 'button',
        '링크': 'link',
        '메뉴': 'menu',
        '네비게이션': 'navigation',
        '헤더': 'header',
        '푸터': 'footer',
        '사이드바': 'sidebar',
        '콘텐츠': 'content',
        '섹션': 'section',
        '블록': 'block',
        '요소': 'element',
        '컴포넌트': 'component',
        '모듈': 'module',
        '패키지': 'package',
        '라이브러리': 'library',
        '프레임워크': 'framework',
        '플러그인': 'plugin',
        '확장': 'extension',
        '애드온': 'addon',
        '위젯': 'widget',
        '도구': 'tool',
        '유틸리티': 'utility',
        '헬퍼': 'helper',
        '함수': 'function',
        '메서드': 'method',
        '클래스': 'class',
        '객체': 'object',
        '인스턴스': 'instance',
        '변수': 'variable',
        '상수': 'constant',
        '파라미터': 'parameter',
        '인수': 'argument',
        '값': 'value',
        '데이터': 'data',
        '정보': 'information',
        '내용': 'content',
        '텍스트': 'text',
        '문자열': 'string',
        '배열': 'array',
        '리스트': 'list',
        '딕셔너리': 'dictionary',
        '맵': 'map',
        '집합': 'set',
        '튜플': 'tuple',
        '구조체': 'struct',
        '레코드': 'record',
        '테이블': 'table',
        '행': 'row',
        '열': 'column',
        '필드': 'field',
        '속성': 'property',
        '특성': 'attribute',
        '키': 'key',
        '값': 'value',
        '쌍': 'pair',
        '관계': 'relationship',
        '연결': 'connection',
        '링크': 'link',
        '참조': 'reference',
        '포인터': 'pointer',
        '주소': 'address',
        '위치': 'location',
        '좌표': 'coordinate',
        '지점': 'point',
        '영역': 'area',
        '범위': 'range',
        '구간': 'interval',
        '기간': 'period',
        '시간': 'time',
        '날짜': 'date',
        '타임스탬프': 'timestamp',
        '로그': 'log',
        '기록': 'record',
        '이력': 'history',
        '추적': 'trace',
        '경로': 'path',
        '루트': 'route',
        '방향': 'direction',
        '순서': 'order',
        '순번': 'number',
        '인덱스': 'index',
        '번호': 'number',
        '식별자': 'identifier',
        'ID': 'ID',
        '아이디': 'ID',
        '코드': 'code',
        '암호': 'code',
        '비밀번호': 'password',
        '키': 'key',
        '토큰': 'token',
        '인증': 'authentication',
        '권한': 'permission',
        '접근': 'access',
        '로그인': 'login',
        '로그아웃': 'logout',
        '세션': 'session',
        '쿠키': 'cookie',
        '캐시': 'cache',
        '버퍼': 'buffer',
        '메모리': 'memory',
        '저장소': 'storage',
        '디스크': 'disk',
        '파일': 'file',
        '폴더': 'folder',
        '디렉터리': 'directory',
        '경로': 'path',
        '확장자': 'extension',
        '형식': 'format',
        '유형': 'type',
        '종류': 'kind',
        '카테고리': 'category',
        '분류': 'classification',
        '그룹': 'group',
        '집단': 'group',
        '팀': 'team',
        '조직': 'organization',
        '회사': 'company',
        '기업': 'enterprise',
        '비즈니스': 'business',
        '사업': 'business',
        '산업': 'industry',
        '분야': 'field',
        '영역': 'domain',
        '부문': 'sector',
        '섹터': 'sector',
        '시장': 'market',
        '고객': 'customer',
        '사용자': 'user',
        '이용자': 'user',
        '회원': 'member',
        '구성원': 'member',
        '참가자': 'participant',
        '참여자': 'participant',
        '방문자': 'visitor',
        '게스트': 'guest',
        '손님': 'guest',
        '친구': 'friend',
        '동료': 'colleague',
        '파트너': 'partner',
        '협력자': 'collaborator',
        '공급자': 'supplier',
        '제공자': 'provider',
        '벤더': 'vendor',
        '판매자': 'seller',
        '구매자': 'buyer',
        '소비자': 'consumer',
        '클라이언트': 'client',
        '서버': 'server',
        '호스트': 'host',
        '게스트': 'guest',
        '관리자': 'administrator',
        '운영자': 'operator',
        '사용자': 'user',
        '개발자': 'developer',
        '프로그래머': 'programmer',
        '디자이너': 'designer',
        '엔지니어': 'engineer',
        '분석가': 'analyst',
        '컨설턴트': 'consultant',
        '전문가': 'expert',
        '스페셜리스트': 'specialist',
        '매니저': 'manager',
        '감독자': 'supervisor',
        '리더': 'leader',
        '팀장': 'team leader',
        '부장': 'manager',
        '이사': 'director',
        '사장': 'president',
        'CEO': 'CEO',
        'CTO': 'CTO',
        'CFO': 'CFO',
        'COO': 'COO',
        'CMO': 'CMO',
        '직원': 'employee',
        '종업원': 'employee',
        '근로자': 'worker',
        '작업자': 'worker',
        '운영자': 'operator',
        '기술자': 'technician',
        '전문가': 'specialist',
        '담당자': 'person in charge',
        '책임자': 'responsible person',
        '대표': 'representative',
        '대리인': 'agent',
        '중개자': 'mediator',
        '조정자': 'coordinator',
        '중재자': 'arbitrator',
        '판매원': 'salesperson',
        '영업사원': 'sales representative',
        '고객서비스': 'customer service',
        '지원': 'support',
    }
    
    for file_path in files_to_process:
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                original_content = content
                
                # Apply translations
                for korean, english in translations.items():
                    if korean in content:
                        content = content.replace(korean, english)
                
                # Save if changed
                if content != original_content:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    print(f"✅ Updated: {file_path}")
                else:
                    print(f"ℹ️  No changes needed: {file_path}")
                    
            except Exception as e:
                print(f"❌ Error processing {file_path}: {e}")

if __name__ == "__main__":
    final_korean_cleanup()
